<?php
/**
 * Hyva Extend Warranty - "Add Warranty" button in Mini-cart
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Hyva_ExtendWarranty
 * @copyright   Copyright (c) 2022 Extend Inc. (https://www.extend.com/)
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */

/** @var \Extend\Warranty\ViewModel\Warranty $viewModel */
$viewModel = $block->getData('viewModel');
?>
<?php if ($viewModel->isExtendEnabled()): ?>
<div class="minicart-warranty-offers"
     :id="'minicart-warranty-offers-' + item.item_id"
     :data-item="item.item_id"
>
    <div x-data="initCartItemWarrantyOffers($el, {
            isInCartPage: false,
            buttonEnabled: <?= $escaper->escapeJs($viewModel->isShoppingCartOffersEnabled() ? 1 : 0) ?>
         })"
         x-init="init()"
         @warranty-data-loaded.window="onGetCartData(event.detail)">
    </div>
</div>
<?php endif; ?>
